In [132]:
import pandas as pd
import numpy as n
df=pd.read_csv(r"C:\Users\shiva\Desktop\DataSCi\DS_Project\adult.csv")

In [2]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [3]:

var = df[(df["capital-gain"] == 0) & (df["occupation"] == "?") & (df["workclass"] == "?")]
#replacing the ? with nan
df.replace("?",np.nan,inplace=True)
df.isna().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [4]:
#Analyzing the occupation having nan value
df['occupation'].isna().sum()
df[df['occupation'].isna()]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K
6,29,NaN,227026,HS-grad,9,Never-married,NaN,Unmarried,Black,Male,0,0,40,United-States,<=50K
13,58,NaN,299831,HS-grad,9,Married-civ-spouse,NaN,Husband,White,Male,0,0,35,United-States,<=50K
22,72,NaN,132015,7th-8th,4,Divorced,NaN,Not-in-family,White,Female,0,0,6,United-States,<=50K
35,65,NaN,191846,HS-grad,9,Married-civ-spouse,NaN,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48811,35,NaN,320084,Bachelors,13,Married-civ-spouse,NaN,Wife,White,Female,0,0,55,United-States,>50K
48812,30,NaN,33811,Bachelors,13,Never-married,NaN,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
48820,71,NaN,287372,Doctorate,16,Married-civ-spouse,NaN,Husband,White,Male,0,0,10,United-States,>50K
48822,41,NaN,202822,HS-grad,9,Separated,NaN,Not-in-family,Black,Female,0,0,32,United-States,<=50K
48823,72,NaN,129912,HS-grad,9,Married-civ-spouse,NaN,Husband,White,Male,0,0,25,United-States,<=50K

In [5]:
#Filtering: show all individuals with income > 50k
df[(df["income"]==">50K") & (df["gender"]=="Male") & (df["age"]>25)]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418,0,40,United-States,>50K
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,48,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48813,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
48814,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
48820,71,NaN,287372,Doctorate,16,Married-civ-spouse,NaN,Husband,White,Male,0,0,10,United-States,>50K
48835,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K

In [6]:
#Filtering with .isin()
df[df["education"].isin(['Bachelors', 'Masters','Doctorate'])]
# this helps in defining segments like top tier job roles and graduated and above , high income or specific occupations

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
11,36,Federal-gov,212465,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
19,40,Private,85019,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,45,NaN,>50K
20,34,Private,107914,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,47,United-States,>50K
23,25,Private,220931,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,43,Peru,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48819,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
48820,71,NaN,287372,Doctorate,16,Married-civ-spouse,NaN,Husband,White,Male,0,0,10,United-States,>50K
48825,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
48834,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
48835,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K

In [7]:
df[df["occupation"].isin(['Exec-managerial','Prof-specialty','Tech-support'])]
#this helps in finding specific occupation

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
19,40,Private,85019,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,45,NaN,>50K
20,34,Private,107914,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,47,United-States,>50K
23,25,Private,220931,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,43,Peru,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48829,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
48834,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
48835,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [8]:
#Filtering with ~ (NOT condition)
#Use ~ (tilde) to reverse any condition.
df[~(df["workclass"]=="Private")]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K
6,29,NaN,227026,HS-grad,9,Never-married,NaN,Unmarried,Black,Male,0,0,40,United-States,<=50K
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
11,36,Federal-gov,212465,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48826,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
48829,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
48830,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
48831,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [9]:
# .str.contains()
# syntax : df[df["col_name"].str.contain("text".case=False,na=False)

# Workclass contains “gov” (federal/local/state)
df["workclass"].unique()
gov_emp=df[df["workclass"].str.contains("gov",case=False,na=False)]
gov_emp

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
11,36,Federal-gov,212465,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
16,20,State-gov,444554,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States,<=50K
30,46,State-gov,106444,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,7688,0,38,United-States,>50K
33,23,Local-gov,258120,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48799,57,Local-gov,110417,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,99999,0,40,United-States,>50K
48821,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
48824,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
48826,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
48830,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K

In [10]:
# Occupation contains “manager”
df[df["occupation"].str.contains("manager",case=False,na=False)]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
30,46,State-gov,106444,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,7688,0,38,United-States,>50K
34,26,Private,43311,HS-grad,9,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,<=50K
49,56,Self-emp-inc,131916,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,0,50,United-States,<=50K
54,38,Private,219446,9th,5,Married-spouse-absent,Exec-managerial,Not-in-family,White,Male,0,0,54,Mexico,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48800,46,Private,364548,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,48,United-States,>50K
48814,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
48817,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
48835,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [11]:
#Native Country contains “India”
df[df["native-country"].str.contains("india",case=False,na=False)]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
398,36,Private,116358,Masters,14,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,45,India,<=50K
564,26,Private,341672,Some-college,10,Never-married,Adm-clerical,Other-relative,Asian-Pac-Islander,Male,0,0,60,India,<=50K
1101,55,Private,176219,Bachelors,13,Married-civ-spouse,Machine-op-inspct,Husband,Asian-Pac-Islander,Male,0,0,40,India,<=50K
1556,33,State-gov,150688,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,50,India,>50K
1593,54,NaN,120781,Doctorate,16,Married-spouse-absent,NaN,Unmarried,Asian-Pac-Islander,Male,0,0,20,India,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46433,48,Private,119471,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
47114,25,Private,110978,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,Asian-Pac-Islander,Female,0,0,37,India,>50K
47152,26,Private,160261,Masters,14,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,0,0,20,India,<=50K
47608,38,State-gov,125499,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,7688,0,60,India,>50K
47638,23,Private,143003,Masters,14,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,1887,50,India,>50K

In [12]:
#People working in private sector and Occupations containing “tech” (e.g., tech-support) and Native country = India (case-insensitive)

df[df["workclass"].str.contains("private",case=False,na=False) & (df["occupation"].str.contains("tech",case=False,na=False) & df["native-country"].str.contains("india",case=False,na=False))]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
5062,22,Private,124483,Bachelors,13,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,2339,40,India,<=50K
5971,39,Private,79586,Some-college,10,Married-civ-spouse,Tech-support,Husband,Asian-Pac-Islander,Male,0,0,35,India,>50K
27665,34,Private,98283,Prof-school,15,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,1564,40,India,>50K
30966,36,Private,110998,Masters,14,Widowed,Tech-support,Unmarried,Asian-Pac-Islander,Female,0,0,40,India,<=50K
37411,49,Private,176341,Bachelors,13,Never-married,Tech-support,Unmarried,Asian-Pac-Islander,Female,0,0,40,India,<=50K
42586,27,Private,207352,Bachelors,13,Married-civ-spouse,Tech-support,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
45912,31,Private,173858,Prof-school,15,Married-civ-spouse,Tech-support,Husband,Asian-Pac-Islander,Male,0,0,40,India,<=50K

In [13]:
#sort_values() — Let’s Rank Some Rows

#Top 10 people witht he highest ccapital - loss
df.sort_values(by="capital-loss",ascending=False)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
25244,90,NaN,77053,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,0,4356,40,United-States,<=50K
31037,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
47062,66,NaN,186061,Some-college,10,Widowed,NaN,Unmarried,Black,Female,0,4356,40,United-States,<=50K
40083,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
36697,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K

In [14]:
#Top 5 oldest people with education = 'Masters'
df[df["education"]=="Masters"].sort_values(by="age",ascending=False).head(5)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
21651,90,Local-gov,227796,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,20051,0,60,United-States,>50K
8427,90,Federal-gov,311184,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Male,0,0,99,United-States,<=50K
36891,90,Private,206667,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,United-States,>50K
21687,90,Private,51744,Masters,14,Never-married,Exec-managerial,Not-in-family,Black,Male,0,0,50,United-States,>50K
35113,90,Private,115306,Masters,14,Never-married,Exec-managerial,Own-child,White,Female,0,0,40,United-States,<=50K

In [15]:
#Sort by hours-per-week, then by age
df.sort_values(by=["hours-per-week","age"],ascending=[False,False]).head(5)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
8427,90,Federal-gov,311184,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Male,0,0,99,United-States,<=50K
31637,90,Private,90523,HS-grad,9,Widowed,Transport-moving,Unmarried,White,Male,0,0,99,United-States,<=50K
8677,73,Self-emp-not-inc,228899,7th-8th,4,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,99,United-States,<=50K
32885,73,Self-emp-not-inc,102510,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,6418,0,99,United-States,>50K
36278,72,Private,268861,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,99,NaN,<=50K

In [16]:
#groupby() — The Brain of Pandas
#It groups rows by one or more columns and then aggregates (like sum, mean, count)
#basic syntax: df.groupby("col_name")["target_column"].agg_functions()

In [17]:
#What is the average hours-per-week for each education level?
df.groupby("education")["hours-per-week"].mean()

education
10th            36.986321
11th            33.952539
12th            35.374429
1st-4th         38.761134
5th-6th         38.923379
7th-8th         39.003141
9th             38.359788
Assoc-acdm      40.809494
Assoc-voc       41.658418
Bachelors       42.482492
Doctorate       46.582492
HS-grad         40.640775
Masters         43.575837
Preschool       36.566265
Prof-school     47.579137
Some-college    38.865784
Name: hours-per-week, dtype: float64

In [18]:
#Which gender has higher average capital-gain?
df.groupby("gender")["capital-gain"].mean().reset_index()

   gender  capital-gain
0  Female    580.726285
1    Male   1326.208300

In [19]:
#What is the total capital-loss by workclass?
df.groupby("workclass")["capital-loss"].sum().sort_values(ascending=False).reset_index()

          workclass  capital-loss
0           Private       2738536
1  Self-emp-not-inc        422300
2         Local-gov        320261
3      Self-emp-inc        281742
4         State-gov        163830
5       Federal-gov        155922
6       Without-pay          1887
7      Never-worked             0

In [20]:
#Mean, min, max hours-per-week per education
df.groupby("education")["hours-per-week"].describe()

                count       mean        std   min    25%   50%    75%   max
education
10th           1389.0  36.986321  13.918007   1.0  30.00  40.0  40.00  99.0
11th           1812.0  33.952539  13.996803   1.0  20.00  40.0  40.00  99.0
12th            657.0  35.374429  12.620268   4.0  25.00  40.0  40.00  99.0
1st-4th         247.0  38.761134  12.226671   4.0  35.00  40.0  40.00  96.0
5th-6th         509.0  38.923379  11.372194   3.0  40.00  40.0  40.00  99.0
7th-8th         955.0  39.003141  14.562775   2.0  35.00  40.0  40.00  99.0
9th             756.0  38.359788  11.464783   1.0  36.75  40.0  40.00  99.0
Assoc-acdm     1601.0  40.809494  12.199101   1.0  40.00  40.0  45.00  99.0
Assoc-voc      2061.0  41.658418  10.943312   1.0  40.00  40.0  45.00  99.0
Bachelors      8025.0  42.482492  11.423058   1.0  40.00  40.0  50.00  99.0
Doctorate       594.0  46.582492  14.919597   1.0  40.00  45.0  55.00  99.0
HS-grad       15784.0  40.640775  11.423842   1.0  40.00  40.0  43.00  99.0
Masters        2657.0  43.575837  12.140942   1.0  40.00  40.0  50.00  99.0
Preschool        83.0  36.566265  11.434002  10.0  30.00  40.0  40.00  75.0
Prof-school     834.0  47.579137  14.983435   2.0  40.00  48.0  55.00  99.0
Some-college  10878.0  38.865784  12.796180   1.0  35.00  40.0  42.75  99.0

In [21]:
#.values_counts()- frequency power tool(return ranked frequency table)
# syntax: df["col_name"].value_counts()

In [22]:
#how many people are there from each workclass?
df["workclass"].value_counts(dropna=False).reset_index()

          workclass  count
0           Private  33906
1  Self-emp-not-inc   3862
2         Local-gov   3136
3               NaN   2799
4         State-gov   1981
5      Self-emp-inc   1695
6       Federal-gov   1432
7       Without-pay     21
8      Never-worked     10

In [23]:
df["workclass"].value_counts(normalize=True).round(2)

workclass
Private             0.74
Self-emp-not-inc    0.08
Local-gov           0.07
State-gov           0.04
Self-emp-inc        0.04
Federal-gov         0.03
Without-pay         0.00
Never-worked        0.00
Name: proportion, dtype: float64

In [24]:
#What's the distribution of income classes?
df["income"].value_counts(normalize=True)

income
<=50K    0.760718
>50K     0.239282
Name: proportion, dtype: float64

In [26]:
#Frequency breakdown of education levels?
df["education"].value_counts(normalize=True).round(2)

education
HS-grad         0.32
Some-college    0.22
Bachelors       0.16
Masters         0.05
Assoc-voc       0.04
11th            0.04
Assoc-acdm      0.03
10th            0.03
7th-8th         0.02
Prof-school     0.02
9th             0.02
12th            0.01
Doctorate       0.01
5th-6th         0.01
1st-4th         0.01
Preschool       0.00
Name: proportion, dtype: float64

In [29]:
#nunique() & .unique() — Know Your Data's Variety
#"How many distinct values does this column have?"
#Want to know if your model is overfitting on a high-cardinality field? nunique() helps.

#Want to filter by known classes? Use .unique() to list options.
df["occupation"].nunique() # no of unique values

14

In [32]:
df["occupation"].unique()
df[df["workclass"].isin(["Private",])]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48836,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [31]:
df["education"].unique()

array(['11th', 'HS-grad', 'Assoc-acdm', 'Some-college', '10th',
       'Prof-school', '7th-8th', 'Bachelors', 'Masters', 'Doctorate',
       '5th-6th', 'Assoc-voc', '9th', '12th', '1st-4th', 'Preschool'],
      dtype=object)

In [ ]:
#.apply() lets you run a function on every row or column — like SQL's CASE WHEN, but way more flexible.
#Used for:
#Feature engineering
#Custom logic
#Conditional mappings
#df['new_col'] = df['column_name'].apply(lambda x: your_logic_here)

In [41]:
df["High_Income"]=df["income"].apply(lambda x: "High" if x== ">50K" else "low" )
df["High_Income"]

0         low
1         low
2        High
3        High
4         low
         ...
48837     low
48838    High
48839     low
48840     low
48841    High
Name: High_Income, Length: 48842, dtype: object

In [43]:
#Flag Senior
df["Senior"]=df['age'].apply(lambda x: 1 if x>=60 else 0)
df["Senior"]

0        0
1        0
2        0
3        0
4        0
        ..
48837    0
48838    0
48839    0
48840    0
48841    0
Name: Senior, Length: 48842, dtype: int64

In [47]:
#Label by work hours
df["workload"]=df["hours-per-week"].apply(lambda x: "Overtime" if x > 50 else "Normal" )
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,High_Income,Senior,workload
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,low,0,Normal
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,low,0,Normal
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,High,0,Normal
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K,High,0,Normal
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K,low,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,low,0,Normal
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,High,0,Normal
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,low,0,Normal
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,low,0,Normal
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,High,0,Normal

In [50]:
df["edu_level"]=df["education"].apply(lambda x: "Pg" if x in ["Masters","Doctorate"] else "UG" )
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,High_Income,Senior,workload,edu_level
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,low,0,Normal,UG
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,low,0,Normal,UG
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,High,0,Normal,UG
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K,High,0,Normal,UG
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K,low,0,Normal,UG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,low,0,Normal,UG
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,High,0,Normal,UG
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,low,0,Normal,UG
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,low,0,Normal,UG
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,High,0,Normal,UG

In [ ]:
#.map() vs .apply()
#— both transform a column, but here's how to choose like a pro:
#✅ Use .map() when:
#You’re mapping specific values
#You want cleaner syntax
#Only working on Series (single column)

#Use .apply() when:
#You need logic, conditions, or multiple conditions
#The transformation is not just 1:1

In [53]:
#map education to levels
df["education"].unique()
edu_map = {
    'Bachelors': 'UG',
    'Some-college': 'UG',
    'HS-grad': 'UG',
    'Masters': 'PG',
    'Doctorate': 'PG'
}
df['edu_level'] = df['education'].map(edu_map).fillna('School')

In [54]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,High_Income,Senior,workload,edu_level
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,low,0,Normal,School
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,low,0,Normal,UG
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,High,0,Normal,School
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K,High,0,Normal,UG
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K,low,0,Normal,UG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,low,0,Normal,School
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,High,0,Normal,UG
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,low,0,Normal,UG
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,low,0,Normal,UG
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,High,0,Normal,UG

In [58]:
#Map race to simplified categories
race_map={
    "White" :"White",
    "Black": "Black",
    "Asian-Pac-Islander":"Asian",
    "Amer-Indian-Eskimo" : "Other",
    "Other":"Other"
}
df["race_group"]=df["race"].map(race_map)
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,High_Income,Senior,workload,edu_level,race_group
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,low,0,Normal,School,Black
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,low,0,Normal,UG,White
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,High,0,Normal,School,White
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K,High,0,Normal,UG,Black
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K,low,0,Normal,UG,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,low,0,Normal,School,White
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,High,0,Normal,UG,White
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,low,0,Normal,UG,White
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,low,0,Normal,UG,White
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,High,0,Normal,UG,White

In [59]:
df.workclass.unique()

array(['Private', 'Local-gov', nan, 'Self-emp-not-inc', 'Federal-gov',
       'State-gov', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [68]:
work_type={
    "Private" : "Corporate",
    'Self-emp-not-inc' : "Entrepreneur",
    'Self-emp-inc' : "Entrepreneur",
    'Local-gov' : "Government",
    'Federal-gov' : "Government",
    'State-gov' : "Government"
    }
df["Work type"]=df["workclass"].map(work_type).fillna("Others")
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,...,capital-loss,hours-per-week,native-country,income,High_Income,Senior,workload,edu_level,race_group,Work type
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,...,0,40,United-States,<=50K,low,0,Normal,School,Black,Corporate
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,...,0,50,United-States,<=50K,low,0,Normal,UG,White,Corporate
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,...,0,40,United-States,>50K,High,0,Normal,School,White,Government
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,...,0,40,United-States,>50K,High,0,Normal,UG,Black,Corporate
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,...,0,30,United-States,<=50K,low,0,Normal,UG,White,Others
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,...,0,38,United-States,<=50K,low,0,Normal,School,White,Corporate
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,...,0,40,United-States,>50K,High,0,Normal,UG,White,Corporate
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,...,0,40,United-States,<=50K,low,0,Normal,UG,White,Corporate
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,...,0,20,United-States,<=50K,low,0,Normal,UG,White,Corporate
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,...,0,40,United-States,>50K,High,0,Normal,UG,White,Entrepreneur

In [ ]:
#.value_counts() + .sort_values()
#This combo is what data analysts use to profile, spot imbalance, and drive insight fast.
#df['column'].value_counts()
#df['column'].value_counts(normalize=True)  # percentages
#You can chain it with .sort_values() if needed:
#df['column'].value_counts().sort_values(ascending=True)

In [70]:
# count how many people per income groups
df['income'].value_counts()

income
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [73]:
#count percentage by education
df["education"].value_counts(normalize=True).round(2)*100

education
HS-grad         32.0
Some-college    22.0
Bachelors       16.0
Masters          5.0
Assoc-voc        4.0
11th             4.0
Assoc-acdm       3.0
10th             3.0
7th-8th          2.0
Prof-school      2.0
9th              2.0
12th             1.0
Doctorate        1.0
5th-6th          1.0
1st-4th          1.0
Preschool        0.0
Name: proportion, dtype: float64

In [75]:
#leaste common workclass
df["workclass"].value_counts().sort_values()

workclass
Never-worked           10
Without-pay            21
Federal-gov          1432
Self-emp-inc         1695
State-gov            1981
Local-gov            3136
Self-emp-not-inc     3862
Private             33906
Name: count, dtype: int64

In [76]:
#list top 5 most common occupation
df["occupation"].value_counts().sort_values(ascending=False).head(5)

occupation
Prof-specialty     6172
Craft-repair       6112
Exec-managerial    6086
Adm-clerical       5611
Sales              5504
Name: count, dtype: int64

In [77]:
#find the number of people working more than 40 hours\week count by income group
df["hours-per-week"]

0        40
1        50
2        40
3        40
4        30
         ..
48837    38
48838    40
48839    40
48840    20
48841    40
Name: hours-per-week, Length: 48842, dtype: int64

In [78]:
# Pivot Tables
""" df.pivot_table(
    values='hours-per-week',
    index='education',
    aggfunc='mean'
)
"""
#avg hours per week by education level
df.pivot_table(
    values="hours-per-week",
    index="education",
    aggfunc="mean"
)

              hours-per-week
education
10th               36.986321
11th               33.952539
12th               35.374429
1st-4th            38.761134
5th-6th            38.923379
7th-8th            39.003141
9th                38.359788
Assoc-acdm         40.809494
Assoc-voc          41.658418
Bachelors          42.482492
Doctorate          46.582492
HS-grad            40.640775
Masters            43.575837
Preschool          36.566265
Prof-school        47.579137
Some-college       38.865784

In [80]:
#Total capital gain by gender & income level
df.pivot_table(
    index="gender",
    values="capital-gain",
    columns="income",
    aggfunc="sum"
)

income    <=50K      >50K
gender
Female  1772249   7630871
Male    3689919  39610782

In [82]:
#count of people per work classs and gender
df.pivot_table(
    index="workclass",
    values="age",
    columns="gender",
    aggfunc="count"
)

gender            Female   Male
workclass
Federal-gov          452    980
Local-gov           1258   1878
Never-worked           3      7
Private            11599  22307
Self-emp-inc         211   1484
Self-emp-not-inc     629   3233
State-gov            763   1218
Without-pay            7     14

In [84]:
# avg hours per week by marital status and income
df.pivot_table(
    index="marital-status",
    columns="income",
    values="hours-per-week",
    aggfunc="mean"
)

income                     <=50K       >50K
marital-status
Divorced               40.431063  47.196721
Married-AF-spouse      37.043478  44.357143
Married-civ-spouse     41.734409  45.259315
Married-spouse-absent  38.842105  47.965517
Never-married          36.426157  46.654843
Separated              39.235500  45.919192
Widowed                32.543885  43.148438

In [88]:
#count of people by education and gender
df.pivot_table(
    index="education",
    columns="gender",
    values="age",
    aggfunc="count"
)

gender        Female   Male
education
10th             457    932
11th             650   1162
12th             211    446
1st-4th           61    186
5th-6th          127    382
7th-8th          239    716
9th              220    536
Assoc-acdm       627    974
Assoc-voc        734   1327
Bachelors       2477   5548
Doctorate        113    481
HS-grad         5097  10687
Masters          845   1812
Preschool         24     59
Prof-school      132    702
Some-college    4178   6700

In [89]:
#mean capital-loss by workclass and income
df.pivot_table(
    index="workclass",
    columns="income",
    values="capital-loss",
    aggfunc="mean"
)

income                <=50K        >50K
workclass
Federal-gov       88.894374  139.919786
Local-gov         73.554550  170.203883
Never-worked       0.000000         NaN
Private           50.422150  189.710437
Self-emp-inc      66.640687  246.583156
Self-emp-not-inc  61.865350  232.130919
State-gov         46.309442  182.330189
Without-pay        0.000000  943.500000

In [92]:
"""  melt() — Wide ➜ Long Format (for EDA, ML, or Viz)
Use Case:
You want to unpivot columns into rows so you can:
Plot multiple variables as one trend
Normalize features for ML
Clean up messy Excel-style wide data
"""

'  melt() — Wide ➜ Long Format (for EDA, ML, or Viz)\nUse Case:\nYou want to unpivot columns into rows so you can:\nPlot multiple variables as one trend\nNormalize features for ML\nClean up messy Excel-style wide data\n'

In [105]:
#Melt capital-gain and capital-loss into a single column for better plotting
df_melted=df.melt(
    id_vars=["education","income"],
    value_vars=["capital-gain","capital-loss"],
    var_name="capital_type",
    value_name="capital_value"
)
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,...,hours-per-week,native-country,income,High_Income,Senior,workload,edu_level,race_group,Work type,age_group
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,...,40,United-States,<=50K,low,0,Normal,School,Black,Corporate,Youth
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,...,50,United-States,<=50K,low,0,Normal,UG,White,Corporate,Young Adults
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,...,40,United-States,>50K,High,0,Normal,School,White,Government,Young Adults
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,...,40,United-States,>50K,High,0,Normal,UG,Black,Corporate,Young Adults
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,...,30,United-States,<=50K,low,0,Normal,UG,White,Others,Youth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,...,38,United-States,<=50K,low,0,Normal,School,White,Corporate,Young Adults
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,...,40,United-States,>50K,High,0,Normal,UG,White,Corporate,Young Adults
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,...,40,United-States,<=50K,low,0,Normal,UG,White,Corporate,Seniors
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,...,20,United-States,<=50K,low,0,Normal,UG,White,Corporate,Youth
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,...,40,United-States,>50K,High,0,Normal,UG,White,Entrepreneur,Seniors

In [109]:
#cut() – Fixed-Range Binning
# Bucket age into fixed ranges
bins=[0,25,45,df["age"].max()]
labels=["Youth","Young Adults","Seniors"]
df["age_group"]=pd.cut(df["age"],bins=bins,labels=labels)
df[["age","age_group"]].head(5)

   age     age_group
0   25         Youth
1   38  Young Adults
2   28  Young Adults
3   44  Young Adults
4   18         Youth

In [117]:
# Bucket people based on hours-per-week
bins=[0,25,75,99]
labels=["low","normal","high"]
df["working_hours"]=pd.cut(df["hours-per-week"],bins=bins,labels=labels)
df.head(5)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,...,native-country,income,High_Income,Senior,workload,edu_level,race_group,Work type,age_group,working_hours
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,...,United-States,<=50K,low,0,Normal,School,Black,Corporate,Youth,normal
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,...,United-States,<=50K,low,0,Normal,UG,White,Corporate,Young Adults,normal
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,...,United-States,>50K,High,0,Normal,School,White,Government,Young Adults,normal
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,...,United-States,>50K,High,0,Normal,UG,Black,Corporate,Young Adults,normal
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,...,United-States,<=50K,low,0,Normal,UG,White,Others,Youth,normal

In [131]:
#Topic: qcut() – Quantile-Based Binning
#Bucket people based on hours-per-week into 4 quartiles
df["workload_quartile"] = pd.qcut(df["hours-per-week"], q=5, labels=["Q1", "Q2", "Q3", "Q4"],duplicates="drop") #remove duplicates edges

In [122]:
df.head(5)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,...,income,High_Income,Senior,workload,edu_level,race_group,Work type,age_group,working_hours,workload_quartile
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,...,<=50K,low,0,Normal,School,Black,Corporate,Youth,normal,Q2
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,...,<=50K,low,0,Normal,UG,White,Corporate,Young Adults,normal,Q4
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,...,>50K,High,0,Normal,School,White,Government,Young Adults,normal,Q2
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,...,>50K,High,0,Normal,UG,Black,Corporate,Young Adults,normal,Q2
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,...,<=50K,low,0,Normal,UG,White,Others,Youth,normal,Q1

In [125]:
"""to categorize capital-gain into:
No Gain (0)
Low Gain (1–5000)
High Gain (>5000)
"""
bins=[-1,0,5000,df["capital-gain"].max()]
labels=["No Gain","Low Gain","High Gain"]
df["capital_cat"]=pd.cut(df["capital-gain"],bins=bins,labels=labels,duplicates="drop")

In [128]:
#using qcut to divide age into decile (10 buckets)
pd.qcut(df["age"],q=10,duplicates="drop")

0          (22.0, 26.0]
1          (37.0, 41.0]
2          (26.0, 30.0]
3          (41.0, 45.0]
4        (16.999, 22.0]
              ...
48837      (26.0, 30.0]
48838      (37.0, 41.0]
48839      (51.0, 58.0]
48840    (16.999, 22.0]
48841      (51.0, 58.0]
Name: age, Length: 48842, dtype: category
Categories (10, interval[float64, right]): [(16.999, 22.0] < (22.0, 26.0] < (26.0, 30.0] < (30.0, 33.0] ... (41.0, 45.0] < (45.0, 51.0] < (51.0, 58.0] < (58.0, 90.0]]

In [129]:
 #Compare how many females vs males fall into the top age quartile
 df["age_q"]=pd.qcut(df["age"],q=4,labels=["Q1","Q2","Q3","Q4"])
 df[df["age_q"]=="Q4"]["gender"].value_counts()

gender
Male      8121
Female    3400
Name: count, dtype: int64